spring:
  application:
    name: gateway

cloud:
  config:
    fail-fast: true

server:
  port: 8080

zuul:
  routes:
    date:
      path: /**
      serviceId: ui

ribbon:
  eureka:
    enabled: true
